### ISSUE TITLE
Pagination: pagesToDisplay does not update on value change inside component

### ISSUE THREAD

**Issue by usolved** [zepdev/zeppelin-element-library-react#13]
In the React component (https://github.com/zepdev/zeppelin-element-library-react/blob/development/packages/zel-react/src/Pagination/Pagination.js) created, there is a configurable prop called "pagesToDisplay" whose variable, once rendered, does not re-render. I.e "pagesToDispaly" Prop is updated inside the component but does not re-render when the value changes. We tried force render but we have not achieved to re-render as expected.

**Comment by cabutler10** [comment]
Reproducible example: https://codesandbox.io/s/optimistic-tereshkova-r7ltw
