### ISSUE TITLE
Feature request for table component: colspan and rowspan

### ISSUE THREAD

**Issue by usolved** [zepdev/zeppelin-element-library-react#21]
Would be great to have support for the **colspan** and **rowspan** attribute on https://github.com/zepdev/zeppelin-element-library-react/tree/development/src/Table.

**Comment by cabutler10** [comment]
@usolved I actually recommend that you use MUI table component and an MUI theme with zel.css instead of this library. We are happy to make this request if you are still using this library and cannot update to the solution above. Which would you prefer?
